"""empty message

Revision ID: 5c7ba22a3ce9
Revises: e1842eb19460
Create Date: 2024-02-22 21:40:38.627492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7ba22a3ce9'
down_revision: Union[str, None] = 'e1842eb19460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('filepath', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'filepath')
    # ### end Alembic commands ###
